query MovieDetails($id: ID!) {
  Movie(movieId: $id) {
    movieId
    budget
    countries
    imdbRating
    plot
    poster
    released
    revenue
    runtime
    title
    year
    in_genre {
      name
    }
    similarMovies {
      title
      year
      runtime
      poster
      imdbRating
      movieId
      in_genre {
        name
      }
    }
  }
}
